---

kind: pipeline

name: Kernel CI

platform:

  os: linux

  arch: amd64

steps:

  - name: build

    image: ubuntu:latest

    commands:

      - apt-get update && apt-get install -y bison build-essential bc bison curl libssl-dev git zip python flex cpio
   
      - git clone https://github.com/lateautumn233/android_kernel_xiaomi_sm8250open.git /drone/build-tools/android_kernel_xiaomi_sm8250 --depth=1 -b rebase3
      
      - git clone https://github.com/lateautumn233/build-scripts /drone/build-tools/build-scripts --branch apollo --depth 1

      - git clone https://github.com/mARk-android/toolchain_mARkclang /drone/build-tools/proton-clang --depth 1

      - git clone https://github.com/lateautumn233/AnyKernel3 /drone/build-tools/anykernel --branch apollo --depth 1
    
      - cd /drone/build-tools/android_kernel_xiaomi_sm8250

      - git submodule init && git submodule update

      - bash /drone/build-tools/build-scripts/build.sh
