---

kind: pipeline

name: lateautumn CI

platform:

  os: linux

  arch: arm64

steps:

  - name: build

    image: ubuntu:latest

    environment:
      id:
        from_secret: id
      ss:
        from_secret: ss

      GIT_SECRET:

        from_secret: GIT_SECRET

    commands:

      - apt update && apt install -y curl hub liblz4-1 libyaml-0-2 p7zip-full gcc g++ bison bc make git zip flex zipalign libssl-dev python python3 libxml2 gcc-aarch64-linux-gnu cpio gcc-arm-linux-gnueabi

      - git clone https://$id:$ss@github.com/lateautumn233/android_kernel_xiaomi_sm8250.git /drone/build-tools/android_kernel_xiaomi_sm8250 --depth=1 -b stable
      
      - git clone https://github.com/lateautumn233/build-scripts /drone/build-tools/build-scripts --branch apollo --depth 1

      - git clone https://github.com/lateautumn233/LateAutumn-clang /drone/build-tools/proton-clang --depth 1

      - git clone https://github.com/lateautumn233/AnyKernel3 /drone/build-tools/anykernel --branch apollo --depth 1
    
      - cd /drone/build-tools/android_kernel_xiaomi_sm8250

      - git submodule init && git submodule update

      - bash /drone/build-tools/build-scripts/build.sh
