name: CI
on:
  push:
    branches: [apollo]
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@master
      
      - name: Install dependency
        run: sudo apt-get update && sudo apt-get install -y bison build-essential bc bison curl libssl-dev git zip python flex cpio

      - name: ci
        run: |
          sudo git clone https://github.com/lateautumn233/android_kernel_xiaomi_sm8250open /drone/build-tools/android_kernel_xiaomi_sm8250 --depth=1 -b rebase3
          sudo git clone https://github.com/hdm9527/build-scripts /drone/build-tools/build-scripts --branch apollo --depth 1
          sudo git clone https://github.com/mARk-android/toolchain_mARkclang /drone/build-tools/proton-clang --depth 1
          sudo git clone https://github.com/lateautumn233/AnyKernel3 /drone/build-tools/anykernel --branch apollo --depth 1
          sudo cd /drone/build-tools/android_kernel_xiaomi_sm8250
          sudo git submodule init && git submodule update
          sudo bash /drone/build-tools/build-scripts/build.sh
      - name : Upload packages
        uses: actions/upload-artifact@master
