name: CI
on:
  push:
    branches: [apollo]
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@master
      
      - name: Install dependency
        run: sudo apt-get update && sudo apt-get install -y bison build-essential bc bison curl libssl-dev git zip python flex cpio zipalign libc6 libc-bin

      - name: ci
        run: |
          git clone https://github.com/lateautumn233/android_kernel_xiaomi_sm8250open build-tools/android_kernel_xiaomi_sm8250 --depth=1 -b rebase3
          git clone https://github.com/hdm9527/build-scripts build-tools/build-scripts --branch apollo --depth 1
          git clone https://github.com/hdm9527/toolchain_mARkclang build-tools/proton-clang --depth 1
          git clone https://github.com/lateautumn233/AnyKernel3 build-tools/anykernel --branch apollo --depth 1
          cd build-tools/android_kernel_xiaomi_sm8250
          git submodule init && sudo git submodule update
          bash ../build-scripts/build.sh
      - name : Upload packages
        uses: actions/upload-artifact@master
